// ─────────────────────────────────────────────────────────────────
//  FinanceAI Proactive Reminder Engine
//  Tự động phân tích dữ liệu giao dịch, ngân sách, mục tiêu
//  và phát hiện các cảnh báo/nhắc nhở tài chính thông minh.
// ─────────────────────────────────────────────────────────────────

import type {
  Transaction,
  Budget,
  FinancialGoal,
  Category,
  Reminder,
} from '../types/finance';

export interface ProactiveEngineOutput {
  criticalReminders: Reminder[];
  detectedReminders: Reminder[];
  upcomingReminders: Reminder[];
  personalReminders: Reminder[];
  allReminders: Reminder[];
}

/**
 * Trợ lý FinanceAI tự động phân tích và tạo ra các Lời nhắc chủ động
 */
export function generateProactiveReminders(
  transactions: Transaction[],
  budgets: Budget[],
  goals: FinancialGoal[],
  categories: Category[],
  userReminders: Reminder[] = [],
): ProactiveEngineOutput {
  const now = new Date();
  const currentMonth = now.getMonth();
  const currentYear = now.getFullYear();
  const currentDay = now.getDate();
  const daysInMonth = new Date(currentYear, currentMonth + 1, 0).getDate();
  const daysRemainingInMonth = daysInMonth - currentDay;

  const categoryMap = new Map<string, Category>(categories.map((c) => [c.id, c]));

  // Danh sách kết quả tổng hợp
  const autoGenerated: Reminder[] = [];

  // ───────────────────────────────────────────────────────────────
  // ① PHÁT HIỆN KHOẢN CHI ĐỊNH KỲ (Recurring Expense Detection)
  // ───────────────────────────────────────────────────────────────
  // Gom nhóm giao dịch expense theo merchantName hoặc description rút gọn
  const expenseTx = transactions.filter((t) => t.type === 'expense');
  const merchantGroups = new Map<string, Transaction[]>();

  expenseTx.forEach((tx) => {
    const key = (tx.merchantName || tx.description || '').trim().toLowerCase();
    if (key.length > 2) {
      const existing = merchantGroups.get(key) || [];
      existing.push(tx);
      merchantGroups.set(key, existing);
    }
  });

  // Tìm các giao dịch xuất hiện liên tiếp/định kỳ (2+ lần ở các tháng khác nhau)
  merchantGroups.forEach((txList, key) => {
    if (txList.length >= 2) {
      // Kiểm tra có các giao dịch ở các tháng khác nhau không
      const months = new Set(txList.map((t) => {
        const d = new Date(t.date);
        return `${d.getFullYear()}-${d.getMonth()}`;
      }));

      if (months.size >= 2) {
        const sample = txList[0];
        const merchantName = sample.merchantName || sample.description;
        const avgAmount = Math.round(
          txList.reduce((sum, t) => sum + t.amount, 0) / txList.length
        );

        // Tính ngày trung bình trong tháng
        const avgDay = Math.round(
          txList.reduce((sum, t) => sum + new Date(t.date).getDate(), 0) / txList.length
        );

        // Dự kiến ngày thanh toán tháng này/tháng sau
        const targetMonth = currentDay > avgDay ? currentMonth + 1 : currentMonth;
        const estimatedDueDate = new Date(currentYear, targetMonth, avgDay)
          .toISOString()
          .split('T')[0];

        const reminderId = `auto-rec-${key.replace(/\s+/g, '-')}`;

        // Kiểm tra xem user đã confirm/dismiss nhắc nhở này chưa
        const isDismissedOrConfirmed = userReminders.some(
          (r) => r.id === reminderId && (r.status === 'dismissed' || r.status === 'confirmed')
        );

        if (!isDismissedOrConfirmed) {
          autoGenerated.push({
            id: reminderId,
            title: `Khoản ${merchantName} có vẻ là giao dịch định kỳ`,
            type: 'auto_recurring',
            categorySection: 'detected',
            amount: avgAmount,
            dueDate: estimatedDueDate,
            categoryId: sample.categoryId,
            status: 'pending',
            frequency: 'monthly',
            isAutoGenerated: true,
            alertLevel: 'info',
            note: `Hệ thống nhận thấy bạn thường chi trả khoản này khoảng ngày ${avgDay} hàng tháng.`,
            detectedPattern: {
              merchantName,
              detectedAmount: avgAmount,
              estimatedDay: avgDay,
              confidence: 0.9,
              description: `Dự kiến thanh toán: ${avgDay}/${targetMonth + 1} • ~${avgAmount.toLocaleString('vi-VN')}đ`,
            },
            createdAt: now.toISOString(),
            updatedAt: now.toISOString(),
          });
        }
      }
    }
  });

  // ───────────────────────────────────────────────────────────────
  // ② TỰ ĐỘNG CẢNH BÁO NGÂN SÁCH (Budget Threshold Detection)
  // ───────────────────────────────────────────────────────────────
  budgets.forEach((bud) => {
    const cat = categoryMap.get(bud.categoryId);
    const catName = cat?.name || 'Hạng mục';
    const pct = Math.round((bud.spent / bud.amount) * 100);
    const remaining = Math.max(0, bud.amount - bud.spent);

    if (pct >= 100) {
      // 🔴 100%+ Over budget
      autoGenerated.push({
        id: `auto-bud-danger-${bud.id}`,
        title: `🔴 Ngân sách ${catName} đã vượt quá giới hạn!`,
        type: 'auto_budget',
        categorySection: 'critical',
        amount: bud.spent - bud.amount,
        dueDate: now.toISOString().split('T')[0],
        categoryId: bud.categoryId,
        budgetId: bud.id,
        status: 'pending',
        isAutoGenerated: true,
        alertLevel: 'danger',
        note: `Bạn đã tiêu ${bud.spent.toLocaleString('vi-VN')}đ / ${bud.amount.toLocaleString('vi-VN')}đ (${pct}% ngân sách ${catName}). Hãy tạm dừng chi tiêu ở mục này.`,
        createdAt: now.toISOString(),
        updatedAt: now.toISOString(),
      });
    } else if (pct >= 85) {
      // 🟠 85% Warning
      autoGenerated.push({
        id: `auto-bud-warn-${bud.id}`,
        title: `⚠️ Bạn đã sử dụng ${pct}% ngân sách ${catName}`,
        type: 'auto_budget',
        categorySection: 'critical',
        amount: remaining,
        dueDate: now.toISOString().split('T')[0],
        categoryId: bud.categoryId,
        budgetId: bud.id,
        status: 'pending',
        isAutoGenerated: true,
        alertLevel: 'warning',
        note: `Đã chi: ${bud.spent.toLocaleString('vi-VN')}đ • Còn lại: ${remaining.toLocaleString('vi-VN')}đ (còn ${daysRemainingInMonth} ngày đến cuối tháng).`,
        createdAt: now.toISOString(),
        updatedAt: now.toISOString(),
      });
    } else if (pct >= 70) {
      // 🟡 70% Light reminder
      autoGenerated.push({
        id: `auto-bud-info-${bud.id}`,
        title: `🟡 Nhắc nhẹ: Ngân sách ${catName} đạt ${pct}%`,
        type: 'auto_budget',
        categorySection: 'detected',
        amount: remaining,
        dueDate: now.toISOString().split('T')[0],
        categoryId: bud.categoryId,
        budgetId: bud.id,
        status: 'pending',
        isAutoGenerated: true,
        alertLevel: 'info',
        note: `Bạn đã sử dụng ${pct}% ngân sách. Còn lại ${remaining.toLocaleString('vi-VN')}đ.`,
        createdAt: now.toISOString(),
        updatedAt: now.toISOString(),
      });
    }
  });

  // ───────────────────────────────────────────────────────────────
  // ③ TỰ ĐỘNG PHÁT HIỆN CHI TIÊU BẤT THƯỜNG (Anomaly Detection)
  // ───────────────────────────────────────────────────────────────
  // Tính tổng chi tháng này theo danh mục
  const currentMonthExpenses = new Map<string, number>();
  const pastMonthsExpenses = new Map<string, number[]>();

  expenseTx.forEach((tx) => {
    const d = new Date(tx.date);
    const m = d.getMonth();
    const y = d.getFullYear();

    if (m === currentMonth && y === currentYear) {
      const curr = currentMonthExpenses.get(tx.categoryId) || 0;
      currentMonthExpenses.set(tx.categoryId, curr + tx.amount);
    } else {
      const history = pastMonthsExpenses.get(tx.categoryId) || [];
      history.push(tx.amount);
      pastMonthsExpenses.set(tx.categoryId, history);
    }
  });

  // Cảnh báo nếu danh mục tháng này tăng đột biến (> 35% so với TB)
  currentMonthExpenses.forEach((currAmount, catId) => {
    const history = pastMonthsExpenses.get(catId);
    const cat = categoryMap.get(catId);
    if (history && history.length > 0 && cat) {
      const avgHistory = history.reduce((a, b) => a + b, 0) / Math.max(1, history.length / 2);
      if (avgHistory > 500_000 && currAmount > avgHistory * 1.35) {
        const increasePct = Math.round(((currAmount - avgHistory) / avgHistory) * 100);
        autoGenerated.push({
          id: `auto-anomaly-cat-${catId}`,
          title: `🤖 Chi tiêu ${cat.name} tăng bất thường (+${increasePct}%)`,
          type: 'auto_anomaly',
          categorySection: 'detected',
          amount: currAmount,
          dueDate: now.toISOString().split('T')[0],
          categoryId: catId,
          status: 'pending',
          isAutoGenerated: true,
          alertLevel: 'warning',
          note: `Chi tiêu ${cat.name} tháng này đang cao hơn khoảng ${increasePct}% so với mức trung bình của bạn (${Math.round(avgHistory).toLocaleString('vi-VN')}đ).`,
          createdAt: now.toISOString(),
          updatedAt: now.toISOString(),
        });
      }
    }
  });

  // Tìm khoản chi mua sắm / lớn nhất gần đây
  const recentLargeExpenses = expenseTx
    .filter((tx) => {
      const txDate = new Date(tx.date);
      const diffDays = (now.getTime() - txDate.getTime()) / (1000 * 3600 * 24);
      return diffDays <= 30 && tx.amount >= 2_000_000;
    })
    .sort((a, b) => b.amount - a.amount);

  if (recentLargeExpenses.length > 0) {
    const topTx = recentLargeExpenses[0];
    const catName = categoryMap.get(topTx.categoryId)?.name || 'Mua sắm';
    autoGenerated.push({
      id: `auto-anomaly-large-${topTx.id}`,
      title: `⚠️ Khoản chi ${topTx.amount.toLocaleString('vi-VN')}đ lớn bất thường`,
      type: 'auto_anomaly',
      categorySection: 'critical',
      amount: topTx.amount,
      dueDate: topTx.date.split('T')[0],
      categoryId: topTx.categoryId,
      status: 'pending',
      isAutoGenerated: true,
      alertLevel: 'warning',
      note: `Bạn vừa chi ${topTx.amount.toLocaleString('vi-VN')}đ cho ${topTx.description} (${catName}). Đây là khoản chi lớn nhất gần đây của bạn.`,
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
    });
  }

  // ───────────────────────────────────────────────────────────────
  // ④ TỰ ĐỘNG NHẮC MỤC TIÊU TÀI CHÍNH (Goal Advice & Delay Warning)
  // ───────────────────────────────────────────────────────────────
  goals.forEach((goal) => {
    if (goal.status === 'active' && goal.currentAmount < goal.targetAmount) {
      const remainingAmount = goal.targetAmount - goal.currentAmount;
      const deadlineDate = new Date(goal.deadline);
      const monthsRemaining = Math.max(
        1,
        (deadlineDate.getFullYear() - currentYear) * 12 + (deadlineDate.getMonth() - currentMonth)
      );

      const recommendedMonthlySaving = Math.round(remainingAmount / monthsRemaining);

      autoGenerated.push({
        id: `auto-goal-adv-${goal.id}`,
        title: `🎯 Bổ sung tiết kiệm cho mục tiêu "${goal.title}"`,
        type: 'auto_goal',
        categorySection: 'detected',
        amount: recommendedMonthlySaving,
        dueDate: now.toISOString().split('T')[0],
        goalId: goal.id,
        status: 'pending',
        isAutoGenerated: true,
        alertLevel: 'info',
        note: `Theo kế hoạch hiện tại, bạn nên tiết kiệm khoảng ${recommendedMonthlySaving.toLocaleString('vi-VN')}đ trong tháng này để đạt mục tiêu đúng hạn (${goal.deadline.split('T')[0]}).`,
        createdAt: now.toISOString(),
        updatedAt: now.toISOString(),
      });
    }
  });

  // ───────────────────────────────────────────────────────────────
  // ⑤ TỔNG HỢP VÀ PHÂN LOẠI DANH SÁCH LỜI NHẮC
  // ───────────────────────────────────────────────────────────────
  const allMergedMap = new Map<string, Reminder>();

  // Thêm lời nhắc từ store
  userReminders.forEach((r) => {
    allMergedMap.set(r.id, r);
  });

  // Thêm lời nhắc tự động mới nếu chưa bị xóa/dismiss
  autoGenerated.forEach((r) => {
    if (!allMergedMap.has(r.id)) {
      allMergedMap.set(r.id, r);
    }
  });

  const allReminders = Array.from(allMergedMap.values()).filter(
    (r) => r.status !== 'dismissed'
  );

  // Phân chia theo từng section giao diện
  const criticalReminders = allReminders.filter(
    (r) => r.categorySection === 'critical' || r.alertLevel === 'danger'
  );

  const detectedReminders = allReminders.filter(
    (r) => r.categorySection === 'detected' || r.type === 'auto_recurring' || r.type === 'auto_anomaly'
  );

  const upcomingReminders = allReminders.filter(
    (r) => r.categorySection === 'upcoming' || r.type === 'auto_bill' || r.type === 'personal'
  ).sort((a, b) => new Date(a.dueDate).getTime() - new Date(b.dueDate).getTime());

  const personalReminders = allReminders.filter(
    (r) => r.type === 'personal' || !r.isAutoGenerated
  );

  return {
    criticalReminders,
    detectedReminders,
    upcomingReminders,
    personalReminders,
    allReminders,
  };
}

/**
 * Tính số ngày còn lại đến hạn
 */
export function getDaysUntilDue(dueDateStr: string): {
  days: number;
  label: string;
  isOverdue: boolean;
  isToday: boolean;
} {
  const due = new Date(dueDateStr);
  const today = new Date();

  due.setHours(0, 0, 0, 0);
  today.setHours(0, 0, 0, 0);

  const diffTime = due.getTime() - today.getTime();
  const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

  if (diffDays === 0) {
    return { days: 0, label: 'Hôm nay', isOverdue: false, isToday: true };
  } else if (diffDays < 0) {
    return { days: Math.abs(diffDays), label: `Quá hạn ${Math.abs(diffDays)} ngày`, isOverdue: true, isToday: false };
  } else {
    return { days: diffDays, label: `${diffDays} ngày nữa`, isOverdue: false, isToday: false };
  }
}
