// ─────────────────────────────────────────────────────────────────
//  Reminders & Bill Calendar Page  –  Proactive Financial Assistant
//  Trợ lý tài chính chủ động FinanceAI
// ─────────────────────────────────────────────────────────────────

import { useState, useMemo } from 'react';
import {
  Bell, AlertTriangle, Sparkles, CheckCircle2,
  Calendar as CalendarIcon, Plus, Check, X,
  Trash2, Edit3, Target, Wallet,
  ExternalLink
} from 'lucide-react';
import { cn, formatVND } from '../utils/helpers';
import {
  useFinanceStore, useTransactions, useBudgets,
  useGoals, useCategories, useReminders
} from '../stores/useFinanceStore';
import {
  generateProactiveReminders, getDaysUntilDue
} from '../utils/reminderEngine';
import type { Reminder } from '../types/finance';

export default function Reminders() {
  const transactions = useTransactions();
  const budgets = useBudgets();
  const goals = useGoals();
  const categories = useCategories();
  const storedReminders = useReminders();

  const addReminder = useFinanceStore((s) => s.addReminder);
  const updateReminder = useFinanceStore((s) => s.updateReminder);
  const deleteReminder = useFinanceStore((s) => s.deleteReminder);
  const confirmRecurringReminder = useFinanceStore((s) => s.confirmRecurringReminder);
  const markReminderPaid = useFinanceStore((s) => s.markReminderPaid);

  // Active Tab state
  const [activeTab, setActiveTab] = useState<'all' | 'critical' | 'detected' | 'upcoming' | 'personal'>('all');

  // Modal states
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false);
  const [editingReminder, setEditingReminder] = useState<Reminder | null>(null);
  const [payingReminder, setPayingReminder] = useState<Reminder | null>(null);
  const [autoAddTxOnPay, setAutoAddTxOnPay] = useState(true);
  const [selectedAnomalyCatId, setSelectedAnomalyCatId] = useState<string | null>(null);

  // New Reminder form state
  const [formData, setFormData] = useState({
    title: '',
    amount: '',
    dueDate: new Date(Date.now() + 86400000 * 3).toISOString().split('T')[0],
    categoryId: categories[0]?.id || '',
    frequency: 'monthly' as 'once' | 'monthly' | 'weekly' | 'yearly',
    note: '',
    alertLevel: 'warning' as 'info' | 'warning' | 'danger',
  });

  // Calculate proactive insights live
  const proactiveOutput = useMemo(() => {
    return generateProactiveReminders(
      transactions,
      budgets,
      goals,
      categories,
      storedReminders
    );
  }, [transactions, budgets, goals, categories, storedReminders]);

  const { criticalReminders, detectedReminders, upcomingReminders, personalReminders, allReminders } = proactiveOutput;

  // Submit Handler for New / Edit Reminder
  const handleSubmitReminder = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.title.trim()) return;

    const numAmount = parseFloat(formData.amount.replace(/\D/g, '')) || 0;

    if (editingReminder) {
      await updateReminder(editingReminder.id, {
        title: formData.title,
        amount: numAmount,
        dueDate: formData.dueDate,
        categoryId: formData.categoryId,
        frequency: formData.frequency,
        note: formData.note,
        alertLevel: formData.alertLevel,
      });
    } else {
      await addReminder({
        title: formData.title,
        type: 'personal',
        categorySection: 'personal',
        amount: numAmount,
        dueDate: formData.dueDate,
        categoryId: formData.categoryId,
        status: 'pending',
        frequency: formData.frequency,
        note: formData.note,
        isAutoGenerated: false,
        alertLevel: formData.alertLevel,
      });
    }

    setIsCreateModalOpen(false);
    setEditingReminder(null);
    setFormData({
      title: '',
      amount: '',
      dueDate: new Date(Date.now() + 86400000 * 3).toISOString().split('T')[0],
      categoryId: categories[0]?.id || '',
      frequency: 'monthly',
      note: '',
      alertLevel: 'warning',
    });
  };

  const handleEdit = (reminder: Reminder) => {
    setEditingReminder(reminder);
    setFormData({
      title: reminder.title,
      amount: reminder.amount.toString(),
      dueDate: reminder.dueDate.split('T')[0],
      categoryId: reminder.categoryId || categories[0]?.id || '',
      frequency: reminder.frequency || 'monthly',
      note: reminder.note || '',
      alertLevel: reminder.alertLevel || 'info',
    });
    setIsCreateModalOpen(true);
  };

  const handleConfirmPay = async () => {
    if (!payingReminder) return;
    await markReminderPaid(payingReminder.id, autoAddTxOnPay);
    setPayingReminder(null);
  };

  const handleDismiss = async (id: string) => {
    await updateReminder(id, { status: 'dismissed' });
  };

  // Find transactions for anomaly inspection modal
  const anomalyCategoryObj = categories.find((c) => c.id === selectedAnomalyCatId);
  const anomalyTransactions = useMemo(() => {
    if (!selectedAnomalyCatId) return [];
    return transactions.filter((t) => t.categoryId === selectedAnomalyCatId && t.type === 'expense');
  }, [selectedAnomalyCatId, transactions]);

  return (
    <div className="space-y-6 pb-12 animate-fade-in">
      {/* ── Top Hero Header ───────────────────────────────────────── */}
      <div className="relative overflow-hidden rounded-2xl bg-slate-900 border border-slate-800 p-6 md:p-8 shadow-2xl">
        <div className="absolute top-0 right-0 -mt-10 -mr-10 w-72 h-72 bg-brand-500/10 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute bottom-0 left-1/3 -mb-10 w-64 h-64 bg-amber-500/10 rounded-full blur-3xl pointer-events-none" />

        <div className="relative flex flex-col md:flex-row md:items-center justify-between gap-6">
          <div className="space-y-2">
            <div className="flex items-center gap-2.5">
              <div className="w-10 h-10 rounded-xl bg-gradient-brand flex items-center justify-center shadow-glow-brand">
                <Bell className="w-5 h-5 text-white" />
              </div>
              <div>
                <div className="flex items-center gap-2">
                  <h1 className="text-2xl md:text-3xl font-bold text-white tracking-tight">Nhắc nhở</h1>
                  <span className="badge bg-brand-500/15 text-brand-400 border border-brand-500/30 text-xs px-2.5 py-0.5 rounded-full flex items-center gap-1">
                    <Sparkles className="w-3 h-3 animate-pulse text-brand-400" /> Trợ lý tài chính chủ động
                  </span>
                </div>
                <p className="text-slate-400 text-sm mt-0.5">Những điều FinanceAI muốn bạn biết & Lịch thanh toán hóa đơn</p>
              </div>
            </div>
          </div>

          {/* Action buttons */}
          <div className="flex items-center gap-3">
            <div className="flex items-center gap-2 bg-slate-800/80 px-4 py-2 rounded-xl border border-slate-700/60">
              <Bell className="w-4 h-4 text-brand-400" />
              <span className="text-xs font-semibold text-slate-300">
                {allReminders.length} Thông báo
              </span>
              {criticalReminders.length > 0 && (
                <span className="bg-danger-500 text-white text-[10px] font-bold px-1.5 py-0.5 rounded-full">
                  {criticalReminders.length} quan trọng
                </span>
              )}
            </div>

            <button
              onClick={() => {
                setEditingReminder(null);
                setFormData({
                  title: '',
                  amount: '',
                  dueDate: new Date(Date.now() + 86400000 * 3).toISOString().split('T')[0],
                  categoryId: categories[0]?.id || '',
                  frequency: 'monthly',
                  note: '',
                  alertLevel: 'warning',
                });
                setIsCreateModalOpen(true);
              }}
              className="btn btn-brand shadow-glow-brand flex items-center gap-2 text-sm font-semibold"
            >
              <Plus className="w-4 h-4" />
              Tạo lời nhắc cá nhân
            </button>
          </div>
        </div>

        {/* Filter Navigation Tabs */}
        <div className="flex items-center gap-2 mt-6 pt-6 border-t border-slate-800/80 overflow-x-auto no-scrollbar">
          <button
            onClick={() => setActiveTab('all')}
            className={cn(
              'px-4 py-2 rounded-xl text-xs font-semibold transition-all whitespace-nowrap flex items-center gap-2',
              activeTab === 'all'
                ? 'bg-brand-500 text-white shadow-brand'
                : 'bg-slate-800/60 text-slate-400 hover:text-slate-200 hover:bg-slate-800'
            )}
          >
            Tất cả ({allReminders.length})
          </button>

          <button
            onClick={() => setActiveTab('critical')}
            className={cn(
              'px-4 py-2 rounded-xl text-xs font-semibold transition-all whitespace-nowrap flex items-center gap-2',
              activeTab === 'critical'
                ? 'bg-danger-500 text-white shadow-danger'
                : 'bg-slate-800/60 text-slate-400 hover:text-slate-200 hover:bg-slate-800'
            )}
          >
            🔴 Cần quan tâm ({criticalReminders.length})
          </button>

          <button
            onClick={() => setActiveTab('detected')}
            className={cn(
              'px-4 py-2 rounded-xl text-xs font-semibold transition-all whitespace-nowrap flex items-center gap-2',
              activeTab === 'detected'
                ? 'bg-brand-500/20 text-brand-300 border border-brand-500/40'
                : 'bg-slate-800/60 text-slate-400 hover:text-slate-200 hover:bg-slate-800'
            )}
          >
            🤖 FinanceAI phát hiện ({detectedReminders.length})
          </button>

          <button
            onClick={() => setActiveTab('upcoming')}
            className={cn(
              'px-4 py-2 rounded-xl text-xs font-semibold transition-all whitespace-nowrap flex items-center gap-2',
              activeTab === 'upcoming'
                ? 'bg-amber-500/20 text-amber-300 border border-amber-500/40'
                : 'bg-slate-800/60 text-slate-400 hover:text-slate-200 hover:bg-slate-800'
            )}
          >
            📅 Sắp tới ({upcomingReminders.length})
          </button>

          <button
            onClick={() => setActiveTab('personal')}
            className={cn(
              'px-4 py-2 rounded-xl text-xs font-semibold transition-all whitespace-nowrap flex items-center gap-2',
              activeTab === 'personal'
                ? 'bg-purple-500/20 text-purple-300 border border-purple-500/40'
                : 'bg-slate-800/60 text-slate-400 hover:text-slate-200 hover:bg-slate-800'
            )}
          >
            👤 Cá nhân ({personalReminders.length})
          </button>
        </div>
      </div>

      {/* ── Main Proactive Content Layout ───────────────────────────── */}
      <div className="space-y-8">
        {/* SECTION 1: 🔴 CẦN QUAN TÂM (CRITICAL ISSUES) */}
        {(activeTab === 'all' || activeTab === 'critical') && criticalReminders.length > 0 && (
          <section className="space-y-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span className="w-2.5 h-2.5 rounded-full bg-danger-500 animate-ping" />
                <h2 className="text-lg font-bold text-slate-100 flex items-center gap-2">
                  🔴 CẦN QUAN TÂM
                </h2>
              </div>
              <span className="text-xs text-slate-400">Các hóa đơn khẩn cấp & Cảnh báo ngân sách chạm trần</span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {criticalReminders.map((rem) => {
                const dueInfo = getDaysUntilDue(rem.dueDate);
                return (
                  <div
                    key={rem.id}
                    className="relative overflow-hidden rounded-xl bg-slate-900/90 border border-danger-500/30 p-5 shadow-lg flex flex-col justify-between group hover:border-danger-500/60 transition-all"
                  >
                    <div className="absolute top-0 left-0 bottom-0 w-1.5 bg-danger-500" />
                    <div>
                      <div className="flex items-start justify-between gap-3">
                        <div className="space-y-1">
                          <div className="flex items-center gap-2">
                            <span className="text-xs font-bold text-danger-400 uppercase tracking-wider">
                              {rem.type === 'auto_budget' ? 'CẢNH BÁO NGÂN SÁCH' : 'HÓA ĐƠN SẮP ĐẾN HẠN'}
                            </span>
                            <span className="badge-danger text-[10px] px-2 py-0.5">
                              {dueInfo.label}
                            </span>
                          </div>
                          <h3 className="text-base font-bold text-slate-100">{rem.title}</h3>
                        </div>
                        {rem.amount > 0 && (
                          <div className="text-right">
                            <p className="text-base font-extrabold text-white">
                              {formatVND(rem.amount)}
                            </p>
                            <p className="text-[11px] text-slate-400">Dự kiến chi</p>
                          </div>
                        )}
                      </div>

                      {rem.note && (
                        <p className="text-xs text-slate-300 mt-2 bg-slate-800/60 p-2.5 rounded-lg border border-slate-700/40">
                          {rem.note}
                        </p>
                      )}
                    </div>

                    <div className="flex items-center justify-between mt-4 pt-3 border-t border-slate-800/80">
                      <span className="text-[11px] text-slate-400">
                        {rem.isAutoGenerated ? '🤖 Tự động phát hiện bởi FinanceAI' : '👤 Lời nhắc cá nhân'}
                      </span>
                      <div className="flex items-center gap-2">
                        <button
                          onClick={() => handleDismiss(rem.id)}
                          className="btn-ghost text-slate-400 hover:text-slate-200 text-xs px-2.5 py-1"
                        >
                          Bỏ qua
                        </button>
                        {rem.status !== 'paid' && (
                          <button
                            onClick={() => setPayingReminder(rem)}
                            className="btn bg-danger-500 hover:bg-danger-600 text-white text-xs px-3 py-1.5 rounded-lg font-semibold flex items-center gap-1.5 shadow-sm"
                          >
                            <Check className="w-3.5 h-3.5" /> Đã thanh toán
                          </button>
                        )}
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </section>
        )}

        {/* SECTION 2: 🤖 FINANCEAI PHÁT HIỆN (AI DETECTED PATTERNS & INSIGHTS) */}
        {(activeTab === 'all' || activeTab === 'detected') && detectedReminders.length > 0 && (
          <section className="space-y-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <div className="w-6 h-6 rounded-lg bg-brand-500/20 border border-brand-500/40 flex items-center justify-center">
                  <Sparkles className="w-3.5 h-3.5 text-brand-400" />
                </div>
                <h2 className="text-lg font-bold text-slate-100">
                  🤖 FINANCEAI PHÁT HIỆN
                </h2>
              </div>
              <span className="text-xs text-slate-400">Tự động đề xuất từ thói quen chi tiêu của bạn</span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {detectedReminders.map((rem) => {
                const isRecurring = rem.type === 'auto_recurring';
                const isAnomaly = rem.type === 'auto_anomaly';
                const isGoal = rem.type === 'auto_goal';

                return (
                  <div
                    key={rem.id}
                    className="relative overflow-hidden rounded-xl bg-surface-900 border border-brand-500/25 p-5 shadow-lg flex flex-col justify-between hover:border-brand-500/50 transition-all group"
                  >
                    <div className="space-y-3">
                      <div className="flex items-start justify-between gap-3">
                        <div className="flex items-center gap-2">
                          <span className="w-2 h-2 rounded-full bg-brand-400 animate-pulse" />
                          <span className="text-xs font-bold text-brand-400 uppercase tracking-wider">
                            {isRecurring ? 'KHOẢN CHI ĐỊNH KỲ' : isAnomaly ? 'CHI TIÊU BẤT THƯỜNG' : isGoal ? 'MỤC TIÊU TÀI CHÍNH' : 'NHẮC NHỞ AI'}
                          </span>
                        </div>
                        {rem.amount > 0 && (
                          <span className="text-sm font-bold text-slate-100 bg-slate-800/80 px-2.5 py-1 rounded-lg border border-slate-700/50">
                            ~{formatVND(rem.amount)}
                          </span>
                        )}
                      </div>

                      <div>
                        <h3 className="text-base font-bold text-slate-100">{rem.title}</h3>
                        {rem.detectedPattern?.description && (
                          <p className="text-xs font-semibold text-brand-300 mt-1">
                            {rem.detectedPattern.description}
                          </p>
                        )}
                        {rem.note && (
                          <p className="text-xs text-slate-300 mt-2 bg-slate-800/40 p-2.5 rounded-lg border border-slate-800">
                            {rem.note}
                          </p>
                        )}
                      </div>
                    </div>

                    {/* Action button bar */}
                    <div className="flex items-center justify-between mt-4 pt-3 border-t border-slate-800/60">
                      <span className="text-[11px] text-slate-400">
                        {isRecurring ? 'Bạn có muốn tự động tạo lịch thanh toán?' : 'Hệ thống tự động phân tích'}
                      </span>

                      <div className="flex items-center gap-2">
                        {isRecurring && (
                          <>
                            <button
                              onClick={() => handleDismiss(rem.id)}
                              className="btn-ghost text-slate-400 hover:text-slate-200 text-xs px-3 py-1.5 rounded-lg"
                            >
                              Bỏ qua
                            </button>
                            <button
                              onClick={() => confirmRecurringReminder(rem.id)}
                              className="btn bg-brand-500 hover:bg-brand-600 text-white text-xs px-3.5 py-1.5 rounded-lg font-semibold flex items-center gap-1.5 shadow-brand"
                            >
                              <Check className="w-3.5 h-3.5" /> Xác nhận
                            </button>
                          </>
                        )}

                        {isAnomaly && rem.categoryId && (
                          <button
                            onClick={() => setSelectedAnomalyCatId(rem.categoryId || null)}
                            className="btn bg-amber-500/20 hover:bg-amber-500/30 text-amber-300 border border-amber-500/40 text-xs px-3 py-1.5 rounded-lg font-semibold flex items-center gap-1.5"
                          >
                            <ExternalLink className="w-3.5 h-3.5" /> Xem chi tiết
                          </button>
                        )}

                        {isGoal && (
                          <a
                            href="/goals"
                            className="btn bg-purple-500/20 hover:bg-purple-500/30 text-purple-300 border border-purple-500/40 text-xs px-3 py-1.5 rounded-lg font-semibold flex items-center gap-1.5"
                          >
                            <Target className="w-3.5 h-3.5" /> Tiết kiệm ngay
                          </a>
                        )}

                        {!isRecurring && !isAnomaly && !isGoal && (
                          <button
                            onClick={() => setPayingReminder(rem)}
                            className="btn bg-brand-500 hover:bg-brand-600 text-white text-xs px-3 py-1.5 rounded-lg font-semibold flex items-center gap-1"
                          >
                            <Check className="w-3.5 h-3.5" /> Xử lý
                          </button>
                        )}
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </section>
        )}

        {/* SECTION 3: 📅 SẮP TỚI (UPCOMING BILL CALENDAR TIMELINE) */}
        {(activeTab === 'all' || activeTab === 'upcoming') && (
          <section className="space-y-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <div className="w-6 h-6 rounded-lg bg-amber-500/20 border border-amber-500/40 flex items-center justify-center">
                  <CalendarIcon className="w-3.5 h-3.5 text-amber-400" />
                </div>
                <h2 className="text-lg font-bold text-slate-100">
                  📅 SẮP TỚI — LỊCH THANH TOÁN HÓA ĐƠN
                </h2>
              </div>
              <span className="text-xs text-slate-400">Danh sách các khoản thanh toán dự kiến theo thứ tự thời gian</span>
            </div>

            <div className="card overflow-hidden border border-slate-800">
              {upcomingReminders.length === 0 ? (
                <div className="text-center py-10">
                  <CalendarIcon className="w-10 h-10 text-slate-600 mx-auto mb-2 opacity-50" />
                  <p className="text-sm font-semibold text-slate-400">Không có hóa đơn sắp tới</p>
                  <p className="text-xs text-slate-500">Tất cả các khoản thanh toán đã được xử lý hoặc chưa đến hạn</p>
                </div>
              ) : (
                <div className="divide-y divide-slate-800/80">
                  {upcomingReminders.map((rem) => {
                    const dueInfo = getDaysUntilDue(rem.dueDate);
                    const catObj = categories.find((c) => c.id === rem.categoryId);

                    return (
                      <div
                        key={rem.id}
                        className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-4 hover:bg-slate-800/40 transition-colors"
                      >
                        <div className="flex items-center gap-4 min-w-0">
                          {/* Date Badge */}
                          <div className="flex flex-col items-center justify-center w-12 h-12 rounded-xl bg-slate-800 border border-slate-700/50 flex-shrink-0">
                            <span className="text-[10px] font-bold text-slate-400 uppercase">
                              T{new Date(rem.dueDate).getMonth() + 1}
                            </span>
                            <span className="text-base font-extrabold text-white leading-none">
                              {new Date(rem.dueDate).getDate()}
                            </span>
                          </div>

                          <div className="min-w-0">
                            <div className="flex items-center gap-2">
                              <h4 className="text-sm font-bold text-slate-100 truncate">{rem.title}</h4>
                              {catObj && (
                                <span
                                  className="text-[10px] px-2 py-0.5 rounded-full font-medium"
                                  style={{ backgroundColor: `${catObj.color}20`, color: catObj.color }}
                                >
                                  {catObj.name}
                                </span>
                              )}
                            </div>
                            <p className="text-xs text-slate-400 mt-0.5 truncate">
                              {rem.note || (rem.frequency === 'monthly' ? 'Thanh toán định kỳ hàng tháng' : 'Hóa đơn')}
                            </p>
                          </div>
                        </div>

                        {/* Amount & Actions */}
                        <div className="flex items-center justify-between sm:justify-end gap-4 border-t sm:border-t-0 pt-2 sm:pt-0 border-slate-800">
                          <div className="text-left sm:text-right">
                            <p className="text-sm font-extrabold text-slate-100">
                              ~{formatVND(rem.amount)}
                            </p>
                            <span className={cn(
                              'text-[10px] font-semibold px-2 py-0.5 rounded-full inline-block mt-0.5',
                              dueInfo.isOverdue ? 'bg-danger-500/20 text-danger-400 border border-danger-500/30' :
                              dueInfo.isToday ? 'bg-amber-500/20 text-amber-300 border border-amber-500/30' :
                              'bg-slate-800 text-slate-400'
                            )}>
                              {dueInfo.label}
                            </span>
                          </div>

                          <div className="flex items-center gap-1.5">
                            {rem.status === 'paid' ? (
                              <span className="badge-success text-xs px-2.5 py-1 flex items-center gap-1">
                                <CheckCircle2 className="w-3.5 h-3.5" /> Đã thanh toán
                              </span>
                            ) : (
                              <button
                                onClick={() => setPayingReminder(rem)}
                                className="btn bg-brand-500/15 hover:bg-brand-500/25 text-brand-400 border border-brand-500/30 text-xs px-3 py-1.5 rounded-lg font-semibold flex items-center gap-1"
                              >
                                <Check className="w-3.5 h-3.5" /> Thanh toán
                              </button>
                            )}

                            {!rem.isAutoGenerated && (
                              <button
                                onClick={() => handleEdit(rem)}
                                className="btn-ghost text-slate-400 hover:text-slate-200 p-1.5 rounded-lg"
                                title="Chỉnh sửa"
                              >
                                <Edit3 className="w-4 h-4" />
                              </button>
                            )}
                          </div>
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          </section>
        )}

        {/* SECTION 4: 👤 LỜI NHẮC CÁ NHÂN (PERSONAL REMINDERS - USER CREATED) */}
        {(activeTab === 'all' || activeTab === 'personal') && (
          <section className="space-y-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <div className="w-6 h-6 rounded-lg bg-purple-500/20 border border-purple-500/40 flex items-center justify-center">
                  <Wallet className="w-3.5 h-3.5 text-purple-400" />
                </div>
                <h2 className="text-lg font-bold text-slate-100">
                  👤 LỜI NHẮC CÁ NHÂN
                </h2>
              </div>
              <button
                onClick={() => {
                  setEditingReminder(null);
                  setFormData({
                    title: '',
                    amount: '',
                    dueDate: new Date(Date.now() + 86400000 * 3).toISOString().split('T')[0],
                    categoryId: categories[0]?.id || '',
                    frequency: 'monthly',
                    note: '',
                    alertLevel: 'warning',
                  });
                  setIsCreateModalOpen(true);
                }}
                className="text-xs text-brand-400 hover:text-brand-300 font-semibold flex items-center gap-1"
              >
                <Plus className="w-3.5 h-3.5" /> Thêm mới
              </button>
            </div>

            {personalReminders.length === 0 ? (
              <div className="card text-center py-8 border border-slate-800">
                <p className="text-sm font-semibold text-slate-400">Chưa có lời nhắc cá nhân nào</p>
                <p className="text-xs text-slate-500 mt-1">
                  Bấm nút <strong>"Tạo lời nhắc cá nhân"</strong> để đặt các thông báo tự tạo như: Nhắc đóng tiền học, Nhắc trả nợ bạn bè...
                </p>
              </div>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {personalReminders.map((rem) => {
                  const dueInfo = getDaysUntilDue(rem.dueDate);

                  return (
                    <div
                      key={rem.id}
                      className="card border border-slate-800 p-4 space-y-3 flex flex-col justify-between hover:border-slate-700 transition-all"
                    >
                      <div className="space-y-2">
                        <div className="flex items-start justify-between gap-2">
                          <h3 className="text-sm font-bold text-slate-100 line-clamp-1">{rem.title}</h3>
                          <span className={cn(
                            'text-[10px] font-semibold px-2 py-0.5 rounded-full flex-shrink-0',
                            rem.status === 'paid' ? 'bg-success-500/20 text-success-400 border border-success-500/30' :
                            dueInfo.isOverdue ? 'bg-danger-500/20 text-danger-400 border border-danger-500/30' :
                            'bg-slate-800 text-slate-300'
                          )}>
                            {rem.status === 'paid' ? 'Đã xong' : dueInfo.label}
                          </span>
                        </div>

                        {rem.amount > 0 && (
                          <p className="text-base font-extrabold text-brand-400">
                            {formatVND(rem.amount)}
                          </p>
                        )}

                        {rem.note && (
                          <p className="text-xs text-slate-400 line-clamp-2 bg-slate-800/40 p-2 rounded-lg">
                            {rem.note}
                          </p>
                        )}
                      </div>

                      <div className="flex items-center justify-between pt-3 border-t border-slate-800 text-xs">
                        <span className="text-slate-500">Hạn: {rem.dueDate.split('T')[0]}</span>

                        <div className="flex items-center gap-1">
                          {rem.status !== 'paid' && (
                            <button
                              onClick={() => setPayingReminder(rem)}
                              className="btn-ghost text-brand-400 hover:bg-brand-500/10 p-1.5 rounded-lg"
                              title="Đánh dấu đã hoàn thành"
                            >
                              <Check className="w-4 h-4" />
                            </button>
                          )}
                          <button
                            onClick={() => handleEdit(rem)}
                            className="btn-ghost text-slate-400 hover:text-slate-200 p-1.5 rounded-lg"
                            title="Sửa"
                          >
                            <Edit3 className="w-4 h-4" />
                          </button>
                          <button
                            onClick={() => deleteReminder(rem.id)}
                            className="btn-ghost text-slate-400 hover:text-danger-400 p-1.5 rounded-lg"
                            title="Xóa"
                          >
                            <Trash2 className="w-4 h-4" />
                          </button>
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </section>
        )}
      </div>

      {/* ── MODAL 1: CREATE / EDIT PERSONAL REMINDER ──────────────── */}
      {isCreateModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm animate-fade-in">
          <div className="relative w-full max-w-md bg-slate-900 border border-slate-800 rounded-2xl shadow-2xl overflow-hidden p-6 space-y-5">
            <div className="flex items-center justify-between border-b border-slate-800 pb-4">
              <h3 className="text-lg font-bold text-slate-100 flex items-center gap-2">
                <Bell className="w-5 h-5 text-brand-400" />
                {editingReminder ? 'Chỉnh sửa lời nhắc' : 'Tạo lời nhắc cá nhân'}
              </h3>
              <button
                onClick={() => setIsCreateModalOpen(false)}
                className="btn-ghost p-1.5 rounded-lg text-slate-400 hover:text-white"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <form onSubmit={handleSubmitReminder} className="space-y-4">
              <div>
                <label className="block text-xs font-semibold text-slate-300 mb-1">
                  Tiêu đề lời nhắc <span className="text-danger-400">*</span>
                </label>
                <input
                  type="text"
                  required
                  placeholder="Ví dụ: Nhắc đóng tiền học, Nhắc trả nợ bạn..."
                  value={formData.title}
                  onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                  className="input w-full"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-semibold text-slate-300 mb-1">
                    Số tiền dự kiến (đ)
                  </label>
                  <input
                    type="number"
                    placeholder="0"
                    value={formData.amount}
                    onChange={(e) => setFormData({ ...formData, amount: e.target.value })}
                    className="input w-full"
                  />
                </div>

                <div>
                  <label className="block text-xs font-semibold text-slate-300 mb-1">
                    Ngày đến hạn <span className="text-danger-400">*</span>
                  </label>
                  <input
                    type="date"
                    required
                    value={formData.dueDate}
                    onChange={(e) => setFormData({ ...formData, dueDate: e.target.value })}
                    className="input w-full"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-semibold text-slate-300 mb-1">
                    Danh mục liên quan
                  </label>
                  <select
                    value={formData.categoryId}
                    onChange={(e) => setFormData({ ...formData, categoryId: e.target.value })}
                    className="input w-full bg-slate-800"
                  >
                    {categories.map((c) => (
                      <option key={c.id} value={c.id}>
                        {c.name}
                      </option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-xs font-semibold text-slate-300 mb-1">
                    Tần suất lặp lại
                  </label>
                  <select
                    value={formData.frequency}
                    onChange={(e) => setFormData({ ...formData, frequency: e.target.value as any })}
                    className="input w-full bg-slate-800"
                  >
                    <option value="once">Chỉ một lần</option>
                    <option value="monthly">Hàng tháng</option>
                    <option value="weekly">Hàng tuần</option>
                    <option value="yearly">Hàng năm</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="block text-xs font-semibold text-slate-300 mb-1">Ghi chú thêm</label>
                <textarea
                  rows={2}
                  placeholder="Nhập thông tin chi tiết hoặc tài khoản nhận..."
                  value={formData.note}
                  onChange={(e) => setFormData({ ...formData, note: e.target.value })}
                  className="input w-full"
                />
              </div>

              <div className="flex items-center justify-end gap-3 pt-3 border-t border-slate-800">
                <button
                  type="button"
                  onClick={() => setIsCreateModalOpen(false)}
                  className="btn-ghost text-xs px-4 py-2"
                >
                  Hủy
                </button>
                <button type="submit" className="btn btn-brand text-xs px-5 py-2 font-semibold">
                  {editingReminder ? 'Cập nhật' : 'Tạo lời nhắc'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* ── MODAL 2: CONFIRM PAYMENT & AUTO RECORD TRANSACTION ─────── */}
      {payingReminder && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-sm animate-fade-in">
          <div className="relative w-full max-w-sm bg-slate-900 border border-slate-800 rounded-2xl shadow-2xl p-6 space-y-4">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-success-500/20 text-success-400 flex items-center justify-center flex-shrink-0">
                <Check className="w-5 h-5" />
              </div>
              <div>
                <h3 className="text-base font-bold text-slate-100">Xác nhận thanh toán</h3>
                <p className="text-xs text-slate-400 truncate">{payingReminder.title}</p>
              </div>
            </div>

            {payingReminder.amount > 0 && (
              <div className="bg-slate-800/60 p-3 rounded-xl border border-slate-700/50 text-center">
                <p className="text-xs text-slate-400">Số tiền thanh toán</p>
                <p className="text-xl font-extrabold text-success-400">
                  {formatVND(payingReminder.amount)}
                </p>
              </div>
            )}

            <div className="flex items-start gap-2 bg-brand-500/10 p-3 rounded-xl border border-brand-500/20">
              <input
                type="checkbox"
                id="autoTxCheck"
                checked={autoAddTxOnPay}
                onChange={(e) => setAutoAddTxOnPay(e.target.checked)}
                className="mt-0.5 rounded text-brand-500 focus:ring-brand-500"
              />
              <label htmlFor="autoTxCheck" className="text-xs text-slate-200 cursor-pointer">
                Tự động ghi chép vào <strong>Lịch sử Giao dịch</strong> dưới dạng một khoản chi tiêu
              </label>
            </div>

            <div className="flex items-center justify-end gap-2 pt-2">
              <button
                onClick={() => setPayingReminder(null)}
                className="btn-ghost text-xs px-3 py-2"
              >
                Hủy
              </button>
              <button
                onClick={handleConfirmPay}
                className="btn bg-success-500 hover:bg-success-600 text-white text-xs px-4 py-2 font-semibold shadow-sm"
              >
                Hoàn thành thanh toán
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ── MODAL 3: ANOMALY CATEGORY INSPECTION ──────────────────── */}
      {selectedAnomalyCatId && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-sm animate-fade-in">
          <div className="relative w-full max-w-lg bg-slate-900 border border-slate-800 rounded-2xl shadow-2xl p-6 space-y-4">
            <div className="flex items-center justify-between border-b border-slate-800 pb-3">
              <h3 className="text-base font-bold text-slate-100 flex items-center gap-2">
                <AlertTriangle className="w-5 h-5 text-amber-400" />
                Chi tiết chi tiêu: {anomalyCategoryObj?.name || 'Hạng mục'}
              </h3>
              <button
                onClick={() => setSelectedAnomalyCatId(null)}
                className="btn-ghost p-1.5 rounded-lg text-slate-400"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            <p className="text-xs text-slate-400">Các giao dịch chi tiêu trong tháng này của hạng mục này:</p>

            <div className="max-h-60 overflow-y-auto space-y-2 pr-1">
              {anomalyTransactions.length === 0 ? (
                <p className="text-xs text-slate-500 py-4 text-center">Chưa có giao dịch chi tiết nào trong tháng này</p>
              ) : (
                anomalyTransactions.map((tx) => (
                  <div key={tx.id} className="flex items-center justify-between p-2.5 rounded-lg bg-slate-800/60 border border-slate-700/40">
                    <div>
                      <p className="text-xs font-bold text-slate-200">{tx.description}</p>
                      <p className="text-[10px] text-slate-400">{tx.date.split('T')[0]} • {tx.merchantName || 'Cửa hàng'}</p>
                    </div>
                    <span className="text-xs font-extrabold text-danger-400">
                      -{formatVND(tx.amount)}
                    </span>
                  </div>
                ))
              )}
            </div>

            <div className="flex items-center justify-end pt-2">
              <button
                onClick={() => setSelectedAnomalyCatId(null)}
                className="btn btn-brand text-xs px-4 py-2"
              >
                Đóng
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
